name: agence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6
  mobx: ^2.3.0
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  geolocator: ^11.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.6.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/agence_logo.png
    - assets/images/product_thumbnail.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/agence_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/agence_logo.png
  min_sdk_android: 21
